export const PAGE_NAME = 'LogReportPage';
export const SET_LOG_REPORT_PAGE_PAGE_STATE = 'SET_LOG_REPORT_PAGE_PAGE_STATE';
export const LOAD_LOG_REPORT_PAGE_LIST_REQUEST = 'LOAD_LOG_REPORT_PAGE_LIST_REQUEST';
export const LOAD_LOG_REPORT_PAGE_LIST_SUCCESS = 'LOAD_LOG_REPORT_PAGE_LIST_SUCCESS';
export const REFRESH_LOG_REPORT_PAGE_LIST_REQUEST = 'REFRESH_LOG_REPORT_PAGE_LIST_REQUEST';
export const REFRESH_LOG_REPORT_PAGE_LIST_SUCCESS = 'REFRESH_LOG_REPORT_PAGE_LIST_SUCCESS';
export const LOAD_LOG_REPORT_PAGE_LIST_FAIL = 'LOAD_LOG_REPORT_PAGE_LIST_FAIL';
