export const PAGE_NAME = 'ListPage';
export const SET_LIST_PAGE_PAGE_STATE = 'SET_LIST_PAGE_PAGE_STATE';
export const LOAD_PAGE_LIST_REQUEST_REQUEST = 'LOAD_PAGE_LIST_REQUEST_REQUEST';
export const LOAD_PAGE_LIST_REQUEST_SUCCESS = 'LOAD_PAGE_LIST_REQUEST_SUCCESS';
export const REFRESH_PAGE_LIST_REQUEST_REQUEST = 'REFRESH_PAGE_LIST_REQUEST_REQUEST';
export const REFRESH_PAGE_LIST_REQUEST_SUCCESS = 'REFRESH_PAGE_LIST_REQUEST_SUCCESS';
export const LOAD_PAGE_LIST_REQUEST_FAIL = 'LOAD_PAGE_LIST_REQUEST_FAIL';
