export const PAGE_NAME = 'ListPage';
export const SET_PAGE_STATE = 'SET_PAGE_STATE';
export const LOAD_LIST_REQUEST = 'LOAD_LIST_REQUEST';
export const LOAD_LIST_SUCCESS = 'LOAD_LIST_SUCCESS';
export const REFRESH_LIST_REQUEST = 'REFRESH_LIST_REQUEST';
export const REFRESH_LIST_SUCCESS = 'REFRESH_LIST_SUCCESS';
export const LOAD_LIST_FAIL = 'LOAD_LIST_FAIL';
