// 如需将 svg 图标作为 React 组件导入，该svg文件的名称应以 -icon.svg 结尾
export { default as tabbarHomeImg } from './tabbar-home.png';
export { default as tabbarHomeSelectedImg } from './tabbar-home-selected.png';
export { default as tabbarAboutImg } from './tabbar-about.png';
export { default as tabbarAboutSelectedImg } from './tabbar-about-selected.png';
export { default as tabbarDemoImg } from './tabbar-demo.png';
export { default as tabbarDemoSelectedImg } from './tabbar-demo-selected.png';
export { default as emptyStateImg } from './empty-state.png';
export { default as errorStateImg } from './error-state.png';
